/**
 * @file choices_32bit.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1887+gab6434f.d20250906 Sat Sep  6 14:40:39 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "choices_32bit.h"

int choices_32bit_foo_pack(
    uint8_t *dst_p,
    const struct choices_32bit_foo_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int8_t*)(&(_temp_union.u8))) = src_p->foo;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int choices_32bit_foo_full_encode(
    uint8_t *dst_p,
    const struct choices_32bit_foo_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int8_t*)(&(_temp_union.u8))) = (src_p->foo);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int choices_32bit_foo_unpack(
    struct choices_32bit_foo_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((int8_t*)(&(dst_p->foo))) = _temp_union.u8;

    return (0);
}

int choices_32bit_foo_full_decode(
    struct choices_32bit_foo_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((int8_t*)(&(dst_p->foo))) = (_temp_union.u8);

    return (0);
}

int choices_32bit_foo_init(struct choices_32bit_foo_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct choices_32bit_foo_t));

    return 0;
}

int8_t choices_32bit_foo_foo_encode(double value)
{
    return (int8_t)(value);
}

double choices_32bit_foo_foo_decode(int8_t value)
{
    return ((double)value);
}

bool choices_32bit_foo_foo_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}
