/**
 * @file floating_point_use_float_32bit.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1887+gab6434f.d20250906 Sat Sep  6 14:40:39 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "floating_point_use_float_32bit.h"

int floating_point_use_float_32bit_message1_pack(
    uint8_t *dst_p,
    const struct floating_point_use_float_32bit_message1_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((double*)(&(_temp_union.u64))) = src_p->signal1;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int floating_point_use_float_32bit_message1_full_encode(
    uint8_t *dst_p,
    const struct floating_point_use_float_32bit_message1_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((double*)(&(_temp_union.u64))) = (src_p->signal1);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int floating_point_use_float_32bit_message1_unpack(
    struct floating_point_use_float_32bit_message1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 32; // r 1
    *((int64_t*)(&(dst_p->signal1))) = _temp_union.u64;

    return (0);
}

int floating_point_use_float_32bit_message1_full_decode(
    struct floating_point_use_float_32bit_message1_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 32; // r 1
    *((int64_t*)(&(dst_p->signal1))) = (_temp_union.u64);

    return (0);
}

int floating_point_use_float_32bit_message1_init(struct floating_point_use_float_32bit_message1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct floating_point_use_float_32bit_message1_t));

    return 0;
}

double floating_point_use_float_32bit_message1_signal1_encode(double value)
{
    return (double)(value);
}

double floating_point_use_float_32bit_message1_signal1_decode(double value)
{
    return ((double)value);
}

bool floating_point_use_float_32bit_message1_signal1_is_in_range(double value)
{
    (void)value;

    return (true);
}

int floating_point_use_float_32bit_message2_pack(
    uint8_t *dst_p,
    const struct floating_point_use_float_32bit_message2_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((float*)(&(_temp_union.u32))) = src_p->signal1;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u32)) << 0)); // w 0
    *((float*)(&(_temp_union.u32))) = src_p->signal2;
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u32)) << 0)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int floating_point_use_float_32bit_message2_full_encode(
    uint8_t *dst_p,
    const struct floating_point_use_float_32bit_message2_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((float*)(&(_temp_union.u32))) = (src_p->signal1);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u32)) << 0)); // w 0
    *((float*)(&(_temp_union.u32))) = (src_p->signal2);
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u32)) << 0)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int floating_point_use_float_32bit_message2_unpack(
    struct floating_point_use_float_32bit_message2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u32 = ((uint32_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    *((int32_t*)(&(dst_p->signal1))) = _temp_union.u32;
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u32 = ((uint32_t)((_temp_buf&0xffffffff) >> 0)); // r 1
    *((int32_t*)(&(dst_p->signal2))) = _temp_union.u32;

    return (0);
}

int floating_point_use_float_32bit_message2_full_decode(
    struct floating_point_use_float_32bit_message2_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u32 = ((uint32_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    *((int32_t*)(&(dst_p->signal1))) = (_temp_union.u32);
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u32 = ((uint32_t)((_temp_buf&0xffffffff) >> 0)); // r 1
    *((int32_t*)(&(dst_p->signal2))) = (_temp_union.u32);

    return (0);
}

int floating_point_use_float_32bit_message2_init(struct floating_point_use_float_32bit_message2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct floating_point_use_float_32bit_message2_t));

    return 0;
}

float floating_point_use_float_32bit_message2_signal1_encode(double value)
{
    return (float)(value);
}

double floating_point_use_float_32bit_message2_signal1_decode(float value)
{
    return ((double)value);
}

bool floating_point_use_float_32bit_message2_signal1_is_in_range(float value)
{
    (void)value;

    return (true);
}

float floating_point_use_float_32bit_message2_signal2_encode(double value)
{
    return (float)(value);
}

double floating_point_use_float_32bit_message2_signal2_decode(float value)
{
    return ((double)value);
}

bool floating_point_use_float_32bit_message2_signal2_is_in_range(float value)
{
    (void)value;

    return (true);
}

int floating_point_use_float_32bit_message3_pack(
    uint8_t *dst_p,
    const struct floating_point_use_float_32bit_message3_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->signal3;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int floating_point_use_float_32bit_message3_full_encode(
    uint8_t *dst_p,
    const struct floating_point_use_float_32bit_message3_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->signal3 - (-0.125)) / (0.001);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int floating_point_use_float_32bit_message3_unpack(
    struct floating_point_use_float_32bit_message3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->signal3))) = _temp_union.u8;

    return (0);
}

int floating_point_use_float_32bit_message3_full_decode(
    struct floating_point_use_float_32bit_message3_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->signal3))) = (_temp_union.u8 * (0.001)) + (-0.125);

    return (0);
}

int floating_point_use_float_32bit_message3_init(struct floating_point_use_float_32bit_message3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct floating_point_use_float_32bit_message3_t));

    return 0;
}

uint8_t floating_point_use_float_32bit_message3_signal3_encode(double value)
{
    return (uint8_t)((value - -0.125) / 0.001);
}

double floating_point_use_float_32bit_message3_signal3_decode(uint8_t value)
{
    return (((double)value * 0.001) + -0.125);
}

bool floating_point_use_float_32bit_message3_signal3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
