/**
 * @file motohawk_32bit.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1887+gab6434f.d20250906 Sat Sep  6 14:40:38 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "motohawk_32bit.h"

int motohawk_32bit_example_message_pack(
    uint8_t *dst_p,
    const struct motohawk_32bit_example_message_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->enable;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u8)) << 7)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->average_radius;
    _temp_buf |= (0x7e & (((uint32_t)(_temp_union.u8)) << 1)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = src_p->temperature;
    _temp_buf |= (0x1 & (_temp_union.u16 >> 11)); // w 0
    _temp_buf |= (0xff00 & (((uint32_t)(_temp_union.u16)) << 5)); // w 0
    _temp_buf |= (0xe00000 & (((uint32_t)(_temp_union.u16)) << 21)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int motohawk_32bit_example_message_full_encode(
    uint8_t *dst_p,
    const struct motohawk_32bit_example_message_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->enable);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u8)) << 7)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->average_radius) / (0.1);
    _temp_buf |= (0x7e & (((uint32_t)(_temp_union.u8)) << 1)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = (src_p->temperature - (250)) / (0.01);
    _temp_buf |= (0x1 & (_temp_union.u16 >> 11)); // w 0
    _temp_buf |= (0xff00 & (((uint32_t)(_temp_union.u16)) << 5)); // w 0
    _temp_buf |= (0xe00000 & (((uint32_t)(_temp_union.u16)) << 21)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int motohawk_32bit_example_message_unpack(
    struct motohawk_32bit_example_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x80) >> 7)); // r 0
    *((uint8_t*)(&(dst_p->enable))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x7e) >> 1)); // r 0
    *((uint8_t*)(&(dst_p->average_radius))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x1)) << 11; // r 0
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff00) >> 5)); // r 0
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xe00000) >> 21)); // r 0
    if (_temp_union.u16 & 0x800) _temp_union.u16 |= 0xf000;
    *((int16_t*)(&(dst_p->temperature))) = _temp_union.u16;

    return (0);
}

int motohawk_32bit_example_message_full_decode(
    struct motohawk_32bit_example_message_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x80) >> 7)); // r 0
    *((uint8_t*)(&(dst_p->enable))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x7e) >> 1)); // r 0
    *((uint8_t*)(&(dst_p->average_radius))) = (_temp_union.u8 * (0.1));
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x1)) << 11; // r 0
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff00) >> 5)); // r 0
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xe00000) >> 21)); // r 0
    if (_temp_union.u16 & 0x800) _temp_union.u16 |= 0xf000;
    *((int16_t*)(&(dst_p->temperature))) = (_temp_union.u16 * (0.01)) + (250);

    return (0);
}

int motohawk_32bit_example_message_init(struct motohawk_32bit_example_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct motohawk_32bit_example_message_t));

    return 0;
}

uint8_t motohawk_32bit_example_message_enable_encode(double value)
{
    return (uint8_t)(value);
}

double motohawk_32bit_example_message_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool motohawk_32bit_example_message_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t motohawk_32bit_example_message_average_radius_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double motohawk_32bit_example_message_average_radius_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool motohawk_32bit_example_message_average_radius_is_in_range(uint8_t value)
{
    return (value <= 50u);
}

int16_t motohawk_32bit_example_message_temperature_encode(double value)
{
    return (int16_t)((value - 250.0) / 0.01);
}

double motohawk_32bit_example_message_temperature_decode(int16_t value)
{
    return (((double)value * 0.01) + 250.0);
}

bool motohawk_32bit_example_message_temperature_is_in_range(int16_t value)
{
    return ((value >= -2048) && (value <= 2047));
}
