/**
 * @file open_actuator_32bit.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1887+gab6434f.d20250906 Sat Sep  6 14:40:39 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "open_actuator_32bit.h"

int open_actuator_32bit_control_cmd_pack(
    uint8_t *dst_p,
    const struct open_actuator_32bit_control_cmd_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->crc8_cmd1;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->target_mode;
    _temp_buf |= (0x700 & (((uint32_t)(_temp_union.u8)) << 8)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->target_motor_id_cmd1;
    _temp_buf |= (0x3000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = src_p->position_cmd_64;
    _temp_buf |= (0xffff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = src_p->torque_command_8;
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x3ff & (((uint32_t)(_temp_union.u16)) << 0)); // w 1
    *((uint8_t*)(&(_temp_union.u8))) = src_p->torque_close_loop_max_32;
    _temp_buf |= (0xfc00 & (((uint32_t)(_temp_union.u8)) << 10)); // w 1
    *((uint8_t*)(&(_temp_union.u8))) = src_p->counter_cmd1;
    _temp_buf |= (0xf0000 & (((uint32_t)(_temp_union.u8)) << 16)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (7);
}

int open_actuator_32bit_control_cmd_full_encode(
    uint8_t *dst_p,
    const struct open_actuator_32bit_control_cmd_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->crc8_cmd1);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->target_mode);
    _temp_buf |= (0x700 & (((uint32_t)(_temp_union.u8)) << 8)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->target_motor_id_cmd1);
    _temp_buf |= (0x3000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = (src_p->position_cmd_64) / (0.0154286);
    _temp_buf |= (0xffff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = (src_p->torque_command_8) / (0.0166667);
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x3ff & (((uint32_t)(_temp_union.u16)) << 0)); // w 1
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->torque_close_loop_max_32) / (0.186666);
    _temp_buf |= (0xfc00 & (((uint32_t)(_temp_union.u8)) << 10)); // w 1
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->counter_cmd1);
    _temp_buf |= (0xf0000 & (((uint32_t)(_temp_union.u8)) << 16)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (7);
}

int open_actuator_32bit_control_cmd_unpack(
    struct open_actuator_32bit_control_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 7u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_cmd1))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x700) >> 8)); // r 0
    *((uint8_t*)(&(dst_p->target_mode))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x3000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->target_motor_id_cmd1))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xffff0000) >> 16)); // r 0
    *((int16_t*)(&(dst_p->position_cmd_64))) = _temp_union.u16;
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u16 = ((uint16_t)((_temp_buf&0x3ff) >> 0)); // r 1
    if (_temp_union.u16 & 0x200) _temp_union.u16 |= 0xfc00;
    *((int16_t*)(&(dst_p->torque_command_8))) = _temp_union.u16;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfc00) >> 10)); // r 1
    *((uint8_t*)(&(dst_p->torque_close_loop_max_32))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf0000) >> 16)); // r 1
    *((uint8_t*)(&(dst_p->counter_cmd1))) = _temp_union.u8;

    return (0);
}

int open_actuator_32bit_control_cmd_full_decode(
    struct open_actuator_32bit_control_cmd_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 7u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_cmd1))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x700) >> 8)); // r 0
    *((uint8_t*)(&(dst_p->target_mode))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x3000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->target_motor_id_cmd1))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xffff0000) >> 16)); // r 0
    *((int16_t*)(&(dst_p->position_cmd_64))) = (_temp_union.u16 * (0.0154286));
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u16 = ((uint16_t)((_temp_buf&0x3ff) >> 0)); // r 1
    if (_temp_union.u16 & 0x200) _temp_union.u16 |= 0xfc00;
    *((int16_t*)(&(dst_p->torque_command_8))) = (_temp_union.u16 * (0.0166667));
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfc00) >> 10)); // r 1
    *((uint8_t*)(&(dst_p->torque_close_loop_max_32))) = (_temp_union.u8 * (0.186666));
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf0000) >> 16)); // r 1
    *((uint8_t*)(&(dst_p->counter_cmd1))) = (_temp_union.u8);

    return (0);
}

int open_actuator_32bit_control_cmd_init(struct open_actuator_32bit_control_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct open_actuator_32bit_control_cmd_t));

    return 0;
}

uint8_t open_actuator_32bit_control_cmd_crc8_cmd1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_control_cmd_crc8_cmd1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_control_cmd_crc8_cmd1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t open_actuator_32bit_control_cmd_target_mode_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_control_cmd_target_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_control_cmd_target_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t open_actuator_32bit_control_cmd_target_motor_id_cmd1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_control_cmd_target_motor_id_cmd1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_control_cmd_target_motor_id_cmd1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int16_t open_actuator_32bit_control_cmd_position_cmd_64_encode(double value)
{
    return (int16_t)(value / 0.0154286);
}

double open_actuator_32bit_control_cmd_position_cmd_64_decode(int16_t value)
{
    return ((double)value * 0.0154286);
}

bool open_actuator_32bit_control_cmd_position_cmd_64_is_in_range(int16_t value)
{
    return ((value >= -29167) && (value <= 29167));
}

int16_t open_actuator_32bit_control_cmd_torque_command_8_encode(double value)
{
    return (int16_t)(value / 0.0166667);
}

double open_actuator_32bit_control_cmd_torque_command_8_decode(int16_t value)
{
    return ((double)value * 0.0166667);
}

bool open_actuator_32bit_control_cmd_torque_command_8_is_in_range(int16_t value)
{
    return ((value >= -480) && (value <= 480));
}

uint8_t open_actuator_32bit_control_cmd_torque_close_loop_max_32_encode(double value)
{
    return (uint8_t)(value / 0.186666);
}

double open_actuator_32bit_control_cmd_torque_close_loop_max_32_decode(uint8_t value)
{
    return ((double)value * 0.186666);
}

bool open_actuator_32bit_control_cmd_torque_close_loop_max_32_is_in_range(uint8_t value)
{
    return (value <= 43u);
}

uint8_t open_actuator_32bit_control_cmd_counter_cmd1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_control_cmd_counter_cmd1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_control_cmd_counter_cmd1_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int open_actuator_32bit_limits_cmd_pack(
    uint8_t *dst_p,
    const struct open_actuator_32bit_limits_cmd_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->crc8_cmd2;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->counter_cmd2;
    _temp_buf |= (0xf000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = src_p->velocity_limit;
    _temp_buf |= (0xffff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = src_p->accel_limit;
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffff & (((uint32_t)(_temp_union.u16)) << 0)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (6);
}

int open_actuator_32bit_limits_cmd_full_encode(
    uint8_t *dst_p,
    const struct open_actuator_32bit_limits_cmd_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->crc8_cmd2);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->counter_cmd2);
    _temp_buf |= (0xf000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = (src_p->velocity_limit);
    _temp_buf |= (0xffff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = (src_p->accel_limit);
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffff & (((uint32_t)(_temp_union.u16)) << 0)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (6);
}

int open_actuator_32bit_limits_cmd_unpack(
    struct open_actuator_32bit_limits_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 6u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_cmd2))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->counter_cmd2))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xffff0000) >> 16)); // r 0
    *((uint16_t*)(&(dst_p->velocity_limit))) = _temp_union.u16;
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xffff) >> 0)); // r 1
    *((uint16_t*)(&(dst_p->accel_limit))) = _temp_union.u16;

    return (0);
}

int open_actuator_32bit_limits_cmd_full_decode(
    struct open_actuator_32bit_limits_cmd_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 6u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_cmd2))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->counter_cmd2))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xffff0000) >> 16)); // r 0
    *((uint16_t*)(&(dst_p->velocity_limit))) = (_temp_union.u16);
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xffff) >> 0)); // r 1
    *((uint16_t*)(&(dst_p->accel_limit))) = (_temp_union.u16);

    return (0);
}

int open_actuator_32bit_limits_cmd_init(struct open_actuator_32bit_limits_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct open_actuator_32bit_limits_cmd_t));

    return 0;
}

uint8_t open_actuator_32bit_limits_cmd_crc8_cmd2_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_limits_cmd_crc8_cmd2_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_limits_cmd_crc8_cmd2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t open_actuator_32bit_limits_cmd_counter_cmd2_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_limits_cmd_counter_cmd2_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_limits_cmd_counter_cmd2_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t open_actuator_32bit_limits_cmd_velocity_limit_encode(double value)
{
    return (uint16_t)(value);
}

double open_actuator_32bit_limits_cmd_velocity_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_limits_cmd_velocity_limit_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t open_actuator_32bit_limits_cmd_accel_limit_encode(double value)
{
    return (uint16_t)(value);
}

double open_actuator_32bit_limits_cmd_accel_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_limits_cmd_accel_limit_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int open_actuator_32bit_control_status_pack(
    uint8_t *dst_p,
    const struct open_actuator_32bit_control_status_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->crc8_stat1;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->counter_stat1;
    _temp_buf |= (0xf000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = src_p->torque_actual;
    _temp_buf |= (0x3ff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->torque_close_loop_actual;
    _temp_buf |= (0xfc000000 & (((uint32_t)(_temp_union.u8)) << 26)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (4);
}

int open_actuator_32bit_control_status_full_encode(
    uint8_t *dst_p,
    const struct open_actuator_32bit_control_status_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->crc8_stat1);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->counter_stat1);
    _temp_buf |= (0xf000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = (src_p->torque_actual) / (0.015625);
    _temp_buf |= (0x3ff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->torque_close_loop_actual) / (0.125);
    _temp_buf |= (0xfc000000 & (((uint32_t)(_temp_union.u8)) << 26)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (4);
}

int open_actuator_32bit_control_status_unpack(
    struct open_actuator_32bit_control_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 4u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_stat1))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->counter_stat1))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0x3ff0000) >> 16)); // r 0
    if (_temp_union.u16 & 0x200) _temp_union.u16 |= 0xfc00;
    *((int16_t*)(&(dst_p->torque_actual))) = _temp_union.u16;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfc000000) >> 26)); // r 0
    *((uint8_t*)(&(dst_p->torque_close_loop_actual))) = _temp_union.u8;

    return (0);
}

int open_actuator_32bit_control_status_full_decode(
    struct open_actuator_32bit_control_status_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 4u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_stat1))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->counter_stat1))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0x3ff0000) >> 16)); // r 0
    if (_temp_union.u16 & 0x200) _temp_union.u16 |= 0xfc00;
    *((int16_t*)(&(dst_p->torque_actual))) = (_temp_union.u16 * (0.015625));
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfc000000) >> 26)); // r 0
    *((uint8_t*)(&(dst_p->torque_close_loop_actual))) = (_temp_union.u8 * (0.125));

    return (0);
}

int open_actuator_32bit_control_status_init(struct open_actuator_32bit_control_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct open_actuator_32bit_control_status_t));

    return 0;
}

uint8_t open_actuator_32bit_control_status_crc8_stat1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_control_status_crc8_stat1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_control_status_crc8_stat1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t open_actuator_32bit_control_status_counter_stat1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_control_status_counter_stat1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_control_status_counter_stat1_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t open_actuator_32bit_control_status_torque_actual_encode(double value)
{
    return (int16_t)(value / 0.015625);
}

double open_actuator_32bit_control_status_torque_actual_decode(int16_t value)
{
    return ((double)value * 0.015625);
}

bool open_actuator_32bit_control_status_torque_actual_is_in_range(int16_t value)
{
    return ((value >= -512) && (value <= 512));
}

uint8_t open_actuator_32bit_control_status_torque_close_loop_actual_encode(double value)
{
    return (uint8_t)(value / 0.125);
}

double open_actuator_32bit_control_status_torque_close_loop_actual_decode(uint8_t value)
{
    return ((double)value * 0.125);
}

bool open_actuator_32bit_control_status_torque_close_loop_actual_is_in_range(uint8_t value)
{
    return (value <= 64u);
}

int open_actuator_32bit_system_status_pack(
    uint8_t *dst_p,
    const struct open_actuator_32bit_system_status_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->crc8_stat2;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->counter_stat2;
    _temp_buf |= (0xf000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->chip_temp;
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u8)) << 16)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (3);
}

int open_actuator_32bit_system_status_full_encode(
    uint8_t *dst_p,
    const struct open_actuator_32bit_system_status_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->crc8_stat2);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->counter_stat2);
    _temp_buf |= (0xf000 & (((uint32_t)(_temp_union.u8)) << 12)); // w 0
    *((uint8_t*)(&(_temp_union.u16))) = (src_p->chip_temp - (-60));
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u16)) << 16)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (3);
}

int open_actuator_32bit_system_status_unpack(
    struct open_actuator_32bit_system_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_stat2))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->counter_stat2))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff0000) >> 16)); // r 0
    *((uint8_t*)(&(dst_p->chip_temp))) = _temp_union.u8;

    return (0);
}

int open_actuator_32bit_system_status_full_decode(
    struct open_actuator_32bit_system_status_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_stat2))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf000) >> 12)); // r 0
    *((uint8_t*)(&(dst_p->counter_stat2))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xff0000) >> 16)); // r 0
    *((uint16_t*)(&(dst_p->chip_temp))) = (_temp_union.u16) + (-60);

    return (0);
}

int open_actuator_32bit_system_status_init(struct open_actuator_32bit_system_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct open_actuator_32bit_system_status_t));

    return 0;
}

uint8_t open_actuator_32bit_system_status_crc8_stat2_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_system_status_crc8_stat2_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_system_status_crc8_stat2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t open_actuator_32bit_system_status_counter_stat2_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_system_status_counter_stat2_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_system_status_counter_stat2_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t open_actuator_32bit_system_status_chip_temp_encode(double value)
{
    return (uint8_t)(value - -60.0);
}

double open_actuator_32bit_system_status_chip_temp_decode(uint8_t value)
{
    return ((double)value + -60.0);
}

bool open_actuator_32bit_system_status_chip_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int open_actuator_32bit_torque_sensor_data_pack(
    uint8_t *dst_p,
    const struct open_actuator_32bit_torque_sensor_data_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->crc8_data1;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->counter_data1;
    _temp_buf |= (0xf00 & (((uint32_t)(_temp_union.u8)) << 8)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = src_p->torque_sense;
    _temp_buf |= (0xfff000 & (((uint32_t)(_temp_union.u16)) << 12)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (3);
}

int open_actuator_32bit_torque_sensor_data_full_encode(
    uint8_t *dst_p,
    const struct open_actuator_32bit_torque_sensor_data_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->crc8_data1);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->counter_data1);
    _temp_buf |= (0xf00 & (((uint32_t)(_temp_union.u8)) << 8)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = (src_p->torque_sense) / (0.01);
    _temp_buf |= (0xfff000 & (((uint32_t)(_temp_union.u16)) << 12)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (3);
}

int open_actuator_32bit_torque_sensor_data_unpack(
    struct open_actuator_32bit_torque_sensor_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_data1))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf00) >> 8)); // r 0
    *((uint8_t*)(&(dst_p->counter_data1))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xfff000) >> 12)); // r 0
    if (_temp_union.u16 & 0x800) _temp_union.u16 |= 0xf000;
    *((int16_t*)(&(dst_p->torque_sense))) = _temp_union.u16;

    return (0);
}

int open_actuator_32bit_torque_sensor_data_full_decode(
    struct open_actuator_32bit_torque_sensor_data_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 3u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xff) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->crc8_data1))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf00) >> 8)); // r 0
    *((uint8_t*)(&(dst_p->counter_data1))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xfff000) >> 12)); // r 0
    if (_temp_union.u16 & 0x800) _temp_union.u16 |= 0xf000;
    *((int16_t*)(&(dst_p->torque_sense))) = (_temp_union.u16 * (0.01));

    return (0);
}

int open_actuator_32bit_torque_sensor_data_init(struct open_actuator_32bit_torque_sensor_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct open_actuator_32bit_torque_sensor_data_t));

    return 0;
}

uint8_t open_actuator_32bit_torque_sensor_data_crc8_data1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_torque_sensor_data_crc8_data1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_torque_sensor_data_crc8_data1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t open_actuator_32bit_torque_sensor_data_counter_data1_encode(double value)
{
    return (uint8_t)(value);
}

double open_actuator_32bit_torque_sensor_data_counter_data1_decode(uint8_t value)
{
    return ((double)value);
}

bool open_actuator_32bit_torque_sensor_data_counter_data1_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t open_actuator_32bit_torque_sensor_data_torque_sense_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double open_actuator_32bit_torque_sensor_data_torque_sense_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool open_actuator_32bit_torque_sensor_data_torque_sense_is_in_range(int16_t value)
{
    return ((value >= -2000) && (value <= 2000));
}
