/**
 * @file padding_bit_order_32bit.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1887+gab6434f.d20250906 Sat Sep  6 14:40:38 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "padding_bit_order_32bit.h"

int padding_bit_order_32bit_msg0_pack(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg0_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->b;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u8)) << 7)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = src_p->a;
    _temp_buf |= (0x7f & (_temp_union.u16 >> 8)); // w 0
    _temp_buf |= (0xff00 & (((uint32_t)(_temp_union.u16)) << 8)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->d;
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u8)) << 7)); // w 1
    *((uint16_t*)(&(_temp_union.u16))) = src_p->c;
    _temp_buf |= (0x7f & (_temp_union.u16 >> 8)); // w 1
    _temp_buf |= (0xff00 & (((uint32_t)(_temp_union.u16)) << 8)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg0_full_encode(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg0_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->b);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u8)) << 7)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = (src_p->a);
    _temp_buf |= (0x7f & (_temp_union.u16 >> 8)); // w 0
    _temp_buf |= (0xff00 & (((uint32_t)(_temp_union.u16)) << 8)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->d);
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u8)) << 7)); // w 1
    *((uint16_t*)(&(_temp_union.u16))) = (src_p->c);
    _temp_buf |= (0x7f & (_temp_union.u16 >> 8)); // w 1
    _temp_buf |= (0xff00 & (((uint32_t)(_temp_union.u16)) << 8)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg0_unpack(
    struct padding_bit_order_32bit_msg0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x80) >> 7)); // r 0
    *((uint8_t*)(&(dst_p->b))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x7f)) << 8; // r 0
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff00) >> 8)); // r 0
    *((uint16_t*)(&(dst_p->a))) = _temp_union.u16;
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x80) >> 7)); // r 1
    *((uint8_t*)(&(dst_p->d))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x7f)) << 8; // r 1
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff00) >> 8)); // r 1
    *((uint16_t*)(&(dst_p->c))) = _temp_union.u16;

    return (0);
}

int padding_bit_order_32bit_msg0_full_decode(
    struct padding_bit_order_32bit_msg0_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x80) >> 7)); // r 0
    *((uint8_t*)(&(dst_p->b))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x7f)) << 8; // r 0
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff00) >> 8)); // r 0
    *((uint16_t*)(&(dst_p->a))) = (_temp_union.u16);
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x80) >> 7)); // r 1
    *((uint8_t*)(&(dst_p->d))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x7f)) << 8; // r 1
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff00) >> 8)); // r 1
    *((uint16_t*)(&(dst_p->c))) = (_temp_union.u16);

    return (0);
}

int padding_bit_order_32bit_msg0_init(struct padding_bit_order_32bit_msg0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct padding_bit_order_32bit_msg0_t));

    return 0;
}

uint8_t padding_bit_order_32bit_msg0_b_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg0_b_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg0_b_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t padding_bit_order_32bit_msg0_a_encode(double value)
{
    return (uint16_t)(value);
}

double padding_bit_order_32bit_msg0_a_decode(uint16_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg0_a_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

uint8_t padding_bit_order_32bit_msg0_d_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg0_d_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg0_d_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t padding_bit_order_32bit_msg0_c_encode(double value)
{
    return (uint16_t)(value);
}

double padding_bit_order_32bit_msg0_c_decode(uint16_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg0_c_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

int padding_bit_order_32bit_msg1_pack(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg1_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->e;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x1 & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = src_p->f;
    _temp_buf |= (0xfffe & (((uint32_t)(_temp_union.u16)) << 1)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->g;
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x1 & (((uint32_t)(_temp_union.u8)) << 0)); // w 1
    *((uint16_t*)(&(_temp_union.u16))) = src_p->h;
    _temp_buf |= (0xfffe & (((uint32_t)(_temp_union.u16)) << 1)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg1_full_encode(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg1_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->e);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x1 & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint16_t*)(&(_temp_union.u16))) = (src_p->f);
    _temp_buf |= (0xfffe & (((uint32_t)(_temp_union.u16)) << 1)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->g);
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x1 & (((uint32_t)(_temp_union.u8)) << 0)); // w 1
    *((uint16_t*)(&(_temp_union.u16))) = (src_p->h);
    _temp_buf |= (0xfffe & (((uint32_t)(_temp_union.u16)) << 1)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg1_unpack(
    struct padding_bit_order_32bit_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x1) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->e))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xfffe) >> 1)); // r 0
    *((uint16_t*)(&(dst_p->f))) = _temp_union.u16;
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x1) >> 0)); // r 1
    *((uint8_t*)(&(dst_p->g))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xfffe) >> 1)); // r 1
    *((uint16_t*)(&(dst_p->h))) = _temp_union.u16;

    return (0);
}

int padding_bit_order_32bit_msg1_full_decode(
    struct padding_bit_order_32bit_msg1_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x1) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->e))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xfffe) >> 1)); // r 0
    *((uint16_t*)(&(dst_p->f))) = (_temp_union.u16);
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x1) >> 0)); // r 1
    *((uint8_t*)(&(dst_p->g))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0xfffe) >> 1)); // r 1
    *((uint16_t*)(&(dst_p->h))) = (_temp_union.u16);

    return (0);
}

int padding_bit_order_32bit_msg1_init(struct padding_bit_order_32bit_msg1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct padding_bit_order_32bit_msg1_t));

    return 0;
}

uint8_t padding_bit_order_32bit_msg1_e_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg1_e_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg1_e_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t padding_bit_order_32bit_msg1_f_encode(double value)
{
    return (uint16_t)(value);
}

double padding_bit_order_32bit_msg1_f_decode(uint16_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg1_f_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

uint8_t padding_bit_order_32bit_msg1_g_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg1_g_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg1_g_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t padding_bit_order_32bit_msg1_h_encode(double value)
{
    return (uint16_t)(value);
}

double padding_bit_order_32bit_msg1_h_decode(uint16_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg1_h_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

int padding_bit_order_32bit_msg2_pack(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg2_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = src_p->i;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xf & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->j;
    _temp_buf |= (0xf0 & (((uint32_t)(_temp_union.u8)) << 4)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = src_p->k;
    _temp_buf |= (0xf00 & (((uint32_t)(_temp_union.u8)) << 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int padding_bit_order_32bit_msg2_full_encode(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg2_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint8_t*)(&(_temp_union.u8))) = (src_p->i);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xf & (((uint32_t)(_temp_union.u8)) << 0)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->j);
    _temp_buf |= (0xf0 & (((uint32_t)(_temp_union.u8)) << 4)); // w 0
    *((uint8_t*)(&(_temp_union.u8))) = (src_p->k);
    _temp_buf |= (0xf00 & (((uint32_t)(_temp_union.u8)) << 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int padding_bit_order_32bit_msg2_unpack(
    struct padding_bit_order_32bit_msg2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->i))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf0) >> 4)); // r 0
    *((uint8_t*)(&(dst_p->j))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf00) >> 8)); // r 0
    *((uint8_t*)(&(dst_p->k))) = _temp_union.u8;

    return (0);
}

int padding_bit_order_32bit_msg2_full_decode(
    struct padding_bit_order_32bit_msg2_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf) >> 0)); // r 0
    *((uint8_t*)(&(dst_p->i))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf0) >> 4)); // r 0
    *((uint8_t*)(&(dst_p->j))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xf00) >> 8)); // r 0
    *((uint8_t*)(&(dst_p->k))) = (_temp_union.u8);

    return (0);
}

int padding_bit_order_32bit_msg2_init(struct padding_bit_order_32bit_msg2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct padding_bit_order_32bit_msg2_t));

    return 0;
}

uint8_t padding_bit_order_32bit_msg2_i_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg2_i_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg2_i_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t padding_bit_order_32bit_msg2_j_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg2_j_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg2_j_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t padding_bit_order_32bit_msg2_k_encode(double value)
{
    return (uint8_t)(value);
}

double padding_bit_order_32bit_msg2_k_decode(uint8_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg2_k_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int padding_bit_order_32bit_msg3_pack(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg3_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint64_t*)(&(_temp_union.u64))) = src_p->l;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 56)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 40)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 24)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 24)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 8)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 8)); // w 1
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg3_full_encode(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg3_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint64_t*)(&(_temp_union.u64))) = (src_p->l);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 56)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 40)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 24)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 24)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 8)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 8)); // w 1
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg3_unpack(
    struct padding_bit_order_32bit_msg3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 56; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 40; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 24; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 8; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 24; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 8; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 8)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 24)); // r 1
    *((uint64_t*)(&(dst_p->l))) = _temp_union.u64;

    return (0);
}

int padding_bit_order_32bit_msg3_full_decode(
    struct padding_bit_order_32bit_msg3_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 56; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 40; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 24; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 8; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 24; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 8; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 8)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 24)); // r 1
    *((uint64_t*)(&(dst_p->l))) = (_temp_union.u64);

    return (0);
}

int padding_bit_order_32bit_msg3_init(struct padding_bit_order_32bit_msg3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct padding_bit_order_32bit_msg3_t));

    return 0;
}

uint64_t padding_bit_order_32bit_msg3_l_encode(double value)
{
    return (uint64_t)(value);
}

double padding_bit_order_32bit_msg3_l_decode(uint64_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg3_l_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int padding_bit_order_32bit_msg4_pack(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg4_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint64_t*)(&(_temp_union.u64))) = src_p->m;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg4_full_encode(
    uint8_t *dst_p,
    const struct padding_bit_order_32bit_msg4_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((uint64_t*)(&(_temp_union.u64))) = (src_p->m);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int padding_bit_order_32bit_msg4_unpack(
    struct padding_bit_order_32bit_msg4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 32; // r 1
    *((uint64_t*)(&(dst_p->m))) = _temp_union.u64;

    return (0);
}

int padding_bit_order_32bit_msg4_full_decode(
    struct padding_bit_order_32bit_msg4_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 32; // r 1
    *((uint64_t*)(&(dst_p->m))) = (_temp_union.u64);

    return (0);
}

int padding_bit_order_32bit_msg4_init(struct padding_bit_order_32bit_msg4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct padding_bit_order_32bit_msg4_t));

    return 0;
}

uint64_t padding_bit_order_32bit_msg4_m_encode(double value)
{
    return (uint64_t)(value);
}

double padding_bit_order_32bit_msg4_m_decode(uint64_t value)
{
    return ((double)value);
}

bool padding_bit_order_32bit_msg4_m_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}
