/**
 * @file signed_32bit.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1887+gab6434f.d20250906 Sat Sep  6 14:40:39 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "signed_32bit.h"

int signed_32bit_message378910_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message378910_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int8_t*)(&(_temp_union.u8))) = src_p->s7;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xfe & (((uint32_t)(_temp_union.u8)) << 1)); // w 0
    *((int8_t*)(&(_temp_union.u8))) = src_p->s8big;
    _temp_buf |= (0x1 & (_temp_union.u8 >> 7)); // w 0
    _temp_buf |= (0xfe00 & (((uint32_t)(_temp_union.u8)) << 9)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = src_p->s9;
    _temp_buf |= (0x3fe0000 & (((uint32_t)(_temp_union.u16)) << 17)); // w 0
    *((int8_t*)(&(_temp_union.u8))) = src_p->s8;
    _temp_buf |= (0xfc000000 & (((uint32_t)(_temp_union.u8)) << 26)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x3 & (_temp_union.u8 >> 6)); // w 1
    *((int8_t*)(&(_temp_union.u8))) = src_p->s3big;
    _temp_buf |= (0xe0 & (((uint32_t)(_temp_union.u8)) << 5)); // w 1
    *((int8_t*)(&(_temp_union.u8))) = src_p->s3;
    _temp_buf |= (0x1c & (((uint32_t)(_temp_union.u8)) << 2)); // w 1
    *((int16_t*)(&(_temp_union.u16))) = src_p->s10big;
    _temp_buf |= (0x100 & (_temp_union.u16 >> 1)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u16)) << 15)); // w 1
    _temp_buf |= (0x80000000 & (((uint32_t)(_temp_union.u16)) << 31)); // w 1
    *((int8_t*)(&(_temp_union.u8))) = src_p->s7big;
    _temp_buf |= (0x7f000000 & (((uint32_t)(_temp_union.u8)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message378910_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message378910_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int8_t*)(&(_temp_union.u8))) = (src_p->s7);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xfe & (((uint32_t)(_temp_union.u8)) << 1)); // w 0
    *((int8_t*)(&(_temp_union.u8))) = (src_p->s8big);
    _temp_buf |= (0x1 & (_temp_union.u8 >> 7)); // w 0
    _temp_buf |= (0xfe00 & (((uint32_t)(_temp_union.u8)) << 9)); // w 0
    *((int16_t*)(&(_temp_union.u16))) = (src_p->s9);
    _temp_buf |= (0x3fe0000 & (((uint32_t)(_temp_union.u16)) << 17)); // w 0
    *((int8_t*)(&(_temp_union.u8))) = (src_p->s8);
    _temp_buf |= (0xfc000000 & (((uint32_t)(_temp_union.u8)) << 26)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x3 & (_temp_union.u8 >> 6)); // w 1
    *((int8_t*)(&(_temp_union.u8))) = (src_p->s3big);
    _temp_buf |= (0xe0 & (((uint32_t)(_temp_union.u8)) << 5)); // w 1
    *((int8_t*)(&(_temp_union.u8))) = (src_p->s3);
    _temp_buf |= (0x1c & (((uint32_t)(_temp_union.u8)) << 2)); // w 1
    *((int16_t*)(&(_temp_union.u16))) = (src_p->s10big);
    _temp_buf |= (0x100 & (_temp_union.u16 >> 1)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u16)) << 15)); // w 1
    _temp_buf |= (0x80000000 & (((uint32_t)(_temp_union.u16)) << 31)); // w 1
    *((int8_t*)(&(_temp_union.u8))) = (src_p->s7big);
    _temp_buf |= (0x7f000000 & (((uint32_t)(_temp_union.u8)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message378910_unpack(
    struct signed_32bit_message378910_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfe) >> 1)); // r 0
    if (_temp_union.u8 & 0x40) _temp_union.u8 |= 0x80;
    *((int8_t*)(&(dst_p->s7))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)(_temp_buf&0x1)) << 7; // r 0
    _temp_union.u8 |= ((uint8_t)((_temp_buf&0xfe00) >> 9)); // r 0
    *((int8_t*)(&(dst_p->s8big))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)((_temp_buf&0x3fe0000) >> 17)); // r 0
    if (_temp_union.u16 & 0x100) _temp_union.u16 |= 0xfe00;
    *((int16_t*)(&(dst_p->s9))) = _temp_union.u16;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfc000000) >> 26)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u8 |= ((uint8_t)(_temp_buf&0x3)) << 6; // r 1
    *((int8_t*)(&(dst_p->s8))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xe0) >> 5)); // r 1
    if (_temp_union.u8 & 0x4) _temp_union.u8 |= 0xf8;
    *((int8_t*)(&(dst_p->s3big))) = _temp_union.u8;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x1c) >> 2)); // r 1
    if (_temp_union.u8 & 0x4) _temp_union.u8 |= 0xf8;
    *((int8_t*)(&(dst_p->s3))) = _temp_union.u8;
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x100)) << 1; // r 1
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff0000) >> 15)); // r 1
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0x80000000) >> 31)); // r 1
    if (_temp_union.u16 & 0x200) _temp_union.u16 |= 0xfc00;
    *((int16_t*)(&(dst_p->s10big))) = _temp_union.u16;
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x7f000000) >> 24)); // r 1
    if (_temp_union.u8 & 0x40) _temp_union.u8 |= 0x80;
    *((int8_t*)(&(dst_p->s7big))) = _temp_union.u8;

    return (0);
}

int signed_32bit_message378910_full_decode(
    struct signed_32bit_message378910_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfe) >> 1)); // r 0
    if (_temp_union.u8 & 0x40) _temp_union.u8 |= 0x80;
    *((int8_t*)(&(dst_p->s7))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)(_temp_buf&0x1)) << 7; // r 0
    _temp_union.u8 |= ((uint8_t)((_temp_buf&0xfe00) >> 9)); // r 0
    *((int8_t*)(&(dst_p->s8big))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)((_temp_buf&0x3fe0000) >> 17)); // r 0
    if (_temp_union.u16 & 0x100) _temp_union.u16 |= 0xfe00;
    *((int16_t*)(&(dst_p->s9))) = (_temp_union.u16);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xfc000000) >> 26)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u8 |= ((uint8_t)(_temp_buf&0x3)) << 6; // r 1
    *((int8_t*)(&(dst_p->s8))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0xe0) >> 5)); // r 1
    if (_temp_union.u8 & 0x4) _temp_union.u8 |= 0xf8;
    *((int8_t*)(&(dst_p->s3big))) = (_temp_union.u8);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x1c) >> 2)); // r 1
    if (_temp_union.u8 & 0x4) _temp_union.u8 |= 0xf8;
    *((int8_t*)(&(dst_p->s3))) = (_temp_union.u8);
    _temp_union.u16 = ((uint16_t)(_temp_buf&0x100)) << 1; // r 1
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0xff0000) >> 15)); // r 1
    _temp_union.u16 |= ((uint16_t)((_temp_buf&0x80000000) >> 31)); // r 1
    if (_temp_union.u16 & 0x200) _temp_union.u16 |= 0xfc00;
    *((int16_t*)(&(dst_p->s10big))) = (_temp_union.u16);
    _temp_union.u8 = ((uint8_t)((_temp_buf&0x7f000000) >> 24)); // r 1
    if (_temp_union.u8 & 0x40) _temp_union.u8 |= 0x80;
    *((int8_t*)(&(dst_p->s7big))) = (_temp_union.u8);

    return (0);
}

int signed_32bit_message378910_init(struct signed_32bit_message378910_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message378910_t));

    return 0;
}

int8_t signed_32bit_message378910_s7_encode(double value)
{
    return (int8_t)(value);
}

double signed_32bit_message378910_s7_decode(int8_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s7_is_in_range(int8_t value)
{
    return ((value >= -64) && (value <= 63));
}

int8_t signed_32bit_message378910_s8big_encode(double value)
{
    return (int8_t)(value);
}

double signed_32bit_message378910_s8big_decode(int8_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s8big_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int16_t signed_32bit_message378910_s9_encode(double value)
{
    return (int16_t)(value);
}

double signed_32bit_message378910_s9_decode(int16_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s9_is_in_range(int16_t value)
{
    return ((value >= -256) && (value <= 255));
}

int8_t signed_32bit_message378910_s8_encode(double value)
{
    return (int8_t)(value);
}

double signed_32bit_message378910_s8_decode(int8_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s8_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t signed_32bit_message378910_s3big_encode(double value)
{
    return (int8_t)(value);
}

double signed_32bit_message378910_s3big_decode(int8_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s3big_is_in_range(int8_t value)
{
    return ((value >= -4) && (value <= 3));
}

int8_t signed_32bit_message378910_s3_encode(double value)
{
    return (int8_t)(value);
}

double signed_32bit_message378910_s3_decode(int8_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s3_is_in_range(int8_t value)
{
    return ((value >= -4) && (value <= 3));
}

int16_t signed_32bit_message378910_s10big_encode(double value)
{
    return (int16_t)(value);
}

double signed_32bit_message378910_s10big_decode(int16_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s10big_is_in_range(int16_t value)
{
    return ((value >= -512) && (value <= 511));
}

int8_t signed_32bit_message378910_s7big_encode(double value)
{
    return (int8_t)(value);
}

double signed_32bit_message378910_s7big_decode(int8_t value)
{
    return ((double)value);
}

bool signed_32bit_message378910_s7big_is_in_range(int8_t value)
{
    return ((value >= -64) && (value <= 63));
}

int signed_32bit_message63big_1_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message63big_1_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s63big;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x7f & (_temp_union.u64 >> 56)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 40)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 24)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 24)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 8)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 8)); // w 1
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63big_1_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message63big_1_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s63big);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0x7f & (_temp_union.u64 >> 56)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 40)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 24)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 24)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 8)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 8)); // w 1
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63big_1_unpack(
    struct signed_32bit_message63big_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0x7f)) << 56; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 40; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 24; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 8; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 24; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 8; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 8)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 24)); // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63big))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message63big_1_full_decode(
    struct signed_32bit_message63big_1_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0x7f)) << 56; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 40; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 24; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 8; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 24; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 8; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 8)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 24)); // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63big))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message63big_1_init(struct signed_32bit_message63big_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message63big_1_t));

    return 0;
}

int64_t signed_32bit_message63big_1_s63big_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message63big_1_s63big_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message63big_1_s63big_is_in_range(int64_t value)
{
    return ((value >= -4611686018427387904ll) && (value <= 4611686018427387903ll));
}

int signed_32bit_message63_1_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message63_1_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s63;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xfffffffe & (((uint32_t)(_temp_union.u64)) << 1)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 31)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63_1_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message63_1_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s63);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xfffffffe & (((uint32_t)(_temp_union.u64)) << 1)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 31)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63_1_unpack(
    struct signed_32bit_message63_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xfffffffe) >> 1)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 31; // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message63_1_full_decode(
    struct signed_32bit_message63_1_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xfffffffe) >> 1)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 31; // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message63_1_init(struct signed_32bit_message63_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message63_1_t));

    return 0;
}

int64_t signed_32bit_message63_1_s63_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message63_1_s63_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message63_1_s63_is_in_range(int64_t value)
{
    return ((value >= -4611686018427387904ll) && (value <= 4611686018427387903ll));
}

int signed_32bit_message63big_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message63big_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s63big;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 55)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 39)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 23)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 7)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 23)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 7)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 9)); // w 1
    _temp_buf |= (0xfe000000 & (((uint32_t)(_temp_union.u64)) << 25)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63big_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message63big_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s63big);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 55)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 39)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 23)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 7)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 23)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 7)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 9)); // w 1
    _temp_buf |= (0xfe000000 & (((uint32_t)(_temp_union.u64)) << 25)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63big_unpack(
    struct signed_32bit_message63big_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 55; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 39; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 23; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 7; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 23; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 7; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 9)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xfe000000) >> 25)); // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63big))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message63big_full_decode(
    struct signed_32bit_message63big_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 55; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 39; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 23; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 7; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 23; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 7; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 9)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xfe000000) >> 25)); // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63big))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message63big_init(struct signed_32bit_message63big_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message63big_t));

    return 0;
}

int64_t signed_32bit_message63big_s63big_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message63big_s63big_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message63big_s63big_is_in_range(int64_t value)
{
    return ((value >= -4611686018427387904ll) && (value <= 4611686018427387903ll));
}

int signed_32bit_message63_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message63_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s63;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x7fffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message63_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s63);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x7fffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message63_unpack(
    struct signed_32bit_message63_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0x7fffffff)) << 32; // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message63_full_decode(
    struct signed_32bit_message63_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0x7fffffff)) << 32; // r 1
    if (_temp_union.u64 & 0x4000000000000000) _temp_union.u64 |= 0x8000000000000000;
    *((int64_t*)(&(dst_p->s63))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message63_init(struct signed_32bit_message63_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message63_t));

    return 0;
}

int64_t signed_32bit_message63_s63_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message63_s63_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message63_s63_is_in_range(int64_t value)
{
    return ((value >= -4611686018427387904ll) && (value <= 4611686018427387903ll));
}

int signed_32bit_message32big_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message32big_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int32_t*)(&(_temp_union.u32))) = src_p->s32big;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u32 >> 24)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u32 >> 8)); // w 0
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u32)) << 8)); // w 0
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u32)) << 24)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int signed_32bit_message32big_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message32big_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int32_t*)(&(_temp_union.u32))) = (src_p->s32big);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u32 >> 24)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u32 >> 8)); // w 0
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u32)) << 8)); // w 0
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u32)) << 24)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int signed_32bit_message32big_unpack(
    struct signed_32bit_message32big_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u32 = ((uint32_t)(_temp_buf&0xff)) << 24; // r 0
    _temp_union.u32 |= ((uint32_t)(_temp_buf&0xff00)) << 8; // r 0
    _temp_union.u32 |= ((uint32_t)((_temp_buf&0xff0000) >> 8)); // r 0
    _temp_union.u32 |= ((uint32_t)((_temp_buf&0xff000000) >> 24)); // r 0
    *((int32_t*)(&(dst_p->s32big))) = _temp_union.u32;

    return (0);
}

int signed_32bit_message32big_full_decode(
    struct signed_32bit_message32big_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u32 = ((uint32_t)(_temp_buf&0xff)) << 24; // r 0
    _temp_union.u32 |= ((uint32_t)(_temp_buf&0xff00)) << 8; // r 0
    _temp_union.u32 |= ((uint32_t)((_temp_buf&0xff0000) >> 8)); // r 0
    _temp_union.u32 |= ((uint32_t)((_temp_buf&0xff000000) >> 24)); // r 0
    *((int32_t*)(&(dst_p->s32big))) = (_temp_union.u32);

    return (0);
}

int signed_32bit_message32big_init(struct signed_32bit_message32big_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message32big_t));

    return 0;
}

int32_t signed_32bit_message32big_s32big_encode(double value)
{
    return (int32_t)(value);
}

double signed_32bit_message32big_s32big_decode(int32_t value)
{
    return ((double)value);
}

bool signed_32bit_message32big_s32big_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int signed_32bit_message33big_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message33big_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s33big;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 25)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 9)); // w 0
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 7)); // w 0
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 23)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u64)) << 7)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message33big_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message33big_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s33big);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 25)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 9)); // w 0
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 7)); // w 0
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 23)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x80 & (((uint32_t)(_temp_union.u64)) << 7)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message33big_unpack(
    struct signed_32bit_message33big_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 25; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 9; // r 0
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 7)); // r 0
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 23)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0x80) >> 7)); // r 1
    if (_temp_union.u64 & 0x100000000) _temp_union.u64 |= 0xfffffffe00000000;
    *((int64_t*)(&(dst_p->s33big))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message33big_full_decode(
    struct signed_32bit_message33big_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 25; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 9; // r 0
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 7)); // r 0
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 23)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0x80) >> 7)); // r 1
    if (_temp_union.u64 & 0x100000000) _temp_union.u64 |= 0xfffffffe00000000;
    *((int64_t*)(&(dst_p->s33big))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message33big_init(struct signed_32bit_message33big_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message33big_t));

    return 0;
}

int64_t signed_32bit_message33big_s33big_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message33big_s33big_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message33big_s33big_is_in_range(int64_t value)
{
    return ((value >= -4294967296ll) && (value <= 4294967295ll));
}

int signed_32bit_message64big_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message64big_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s64big;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 56)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 40)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 24)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 24)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 8)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 8)); // w 1
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message64big_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message64big_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s64big);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xff & (_temp_union.u64 >> 56)); // w 0
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 40)); // w 0
    _temp_buf |= (0xff0000 & (_temp_union.u64 >> 24)); // w 0
    _temp_buf |= (0xff000000 & (_temp_union.u64 >> 8)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xff & (_temp_union.u64 >> 24)); // w 1
    _temp_buf |= (0xff00 & (_temp_union.u64 >> 8)); // w 1
    _temp_buf |= (0xff0000 & (((uint32_t)(_temp_union.u64)) << 8)); // w 1
    _temp_buf |= (0xff000000 & (((uint32_t)(_temp_union.u64)) << 24)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message64big_unpack(
    struct signed_32bit_message64big_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 56; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 40; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 24; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 8; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 24; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 8; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 8)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 24)); // r 1
    *((int64_t*)(&(dst_p->s64big))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message64big_full_decode(
    struct signed_32bit_message64big_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)(_temp_buf&0xff)) << 56; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 40; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff0000)) << 24; // r 0
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff000000)) << 8; // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff)) << 24; // r 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xff00)) << 8; // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff0000) >> 8)); // r 1
    _temp_union.u64 |= ((uint64_t)((_temp_buf&0xff000000) >> 24)); // r 1
    *((int64_t*)(&(dst_p->s64big))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message64big_init(struct signed_32bit_message64big_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message64big_t));

    return 0;
}

int64_t signed_32bit_message64big_s64big_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message64big_s64big_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message64big_s64big_is_in_range(int64_t value)
{
    (void)value;

    return (true);
}

int signed_32bit_message64_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message64_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s64;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message64_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message64_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s64);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0xffffffff & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message64_unpack(
    struct signed_32bit_message64_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 32; // r 1
    *((int64_t*)(&(dst_p->s64))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message64_full_decode(
    struct signed_32bit_message64_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0xffffffff)) << 32; // r 1
    *((int64_t*)(&(dst_p->s64))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message64_init(struct signed_32bit_message64_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message64_t));

    return 0;
}

int64_t signed_32bit_message64_s64_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message64_s64_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message64_s64_is_in_range(int64_t value)
{
    (void)value;

    return (true);
}

int signed_32bit_message33_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message33_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = src_p->s33;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x1 & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message33_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message33_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int64_t*)(&(_temp_union.u64))) = (src_p->s33);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u64)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0
    _temp_buf = ((uint32_t*)(dst_p))[1]; // l 1
    _temp_buf |= (0x1 & (_temp_union.u64 >> 32)); // w 1
    ((uint32_t*)(dst_p))[1] = _temp_buf; // s 1

    return (8);
}

int signed_32bit_message33_unpack(
    struct signed_32bit_message33_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0x1)) << 32; // r 1
    if (_temp_union.u64 & 0x100000000) _temp_union.u64 |= 0xfffffffe00000000;
    *((int64_t*)(&(dst_p->s33))) = _temp_union.u64;

    return (0);
}

int signed_32bit_message33_full_decode(
    struct signed_32bit_message33_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; uint64_t u64; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u64 = ((uint64_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    _temp_buf = ((uint32_t*)(src_p))[1]; // l 1
    _temp_union.u64 |= ((uint64_t)(_temp_buf&0x1)) << 32; // r 1
    if (_temp_union.u64 & 0x100000000) _temp_union.u64 |= 0xfffffffe00000000;
    *((int64_t*)(&(dst_p->s33))) = (_temp_union.u64);

    return (0);
}

int signed_32bit_message33_init(struct signed_32bit_message33_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message33_t));

    return 0;
}

int64_t signed_32bit_message33_s33_encode(double value)
{
    return (int64_t)(value);
}

double signed_32bit_message33_s33_decode(int64_t value)
{
    return ((double)value);
}

bool signed_32bit_message33_s33_is_in_range(int64_t value)
{
    return ((value >= -4294967296ll) && (value <= 4294967295ll));
}

int signed_32bit_message32_pack(
    uint8_t *dst_p,
    const struct signed_32bit_message32_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int32_t*)(&(_temp_union.u32))) = src_p->s32;
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u32)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int signed_32bit_message32_full_encode(
    uint8_t *dst_p,
    const struct signed_32bit_message32_d *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    *((int32_t*)(&(_temp_union.u32))) = (src_p->s32);
    _temp_buf = ((uint32_t*)(dst_p))[0]; // l 0
    _temp_buf |= (0xffffffff & (((uint32_t)(_temp_union.u32)) << 0)); // w 0
    ((uint32_t*)(dst_p))[0] = _temp_buf; // s 0

    return (8);
}

int signed_32bit_message32_unpack(
    struct signed_32bit_message32_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u32 = ((uint32_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    *((int32_t*)(&(dst_p->s32))) = _temp_union.u32;

    return (0);
}

int signed_32bit_message32_full_decode(
    struct signed_32bit_message32_d *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t _temp_buf;
    union {uint8_t u8; uint16_t u16; uint32_t u32; } _temp_union;

    if (size < 8u) {
        return (-EINVAL);
    }

    _temp_buf = ((uint32_t*)(src_p))[0]; // l 0
    _temp_union.u32 = ((uint32_t)((_temp_buf&0xffffffff) >> 0)); // r 0
    *((int32_t*)(&(dst_p->s32))) = (_temp_union.u32);

    return (0);
}

int signed_32bit_message32_init(struct signed_32bit_message32_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct signed_32bit_message32_t));

    return 0;
}

int32_t signed_32bit_message32_s32_encode(double value)
{
    return (int32_t)(value);
}

double signed_32bit_message32_s32_decode(int32_t value)
{
    return ((double)value);
}

bool signed_32bit_message32_s32_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}
